### ISSUE TITLE
pre-process synchronized audio-video streams

### ISSUE THREAD

**Issue by LindgeW** [sectum1919/CNVSRC2024Baseline#1]
Hi,

Thanks for your great work! Could you give more details about how to pre-process the synchronized audio-video input streams, i.e., how to achieve the temporal alignment between audio and video streams exactly?

**Comment by sectum1919** [comment]
Thanks, we use SyncNet for pre-processing. You can refer to ```https://github.com/sectum1919/cncvs_data_collector/blob/speech/syncnet_filter.py``` for more information.
